# Dependencies
highlighter:      pygments

# Setup
title:            Ye Yuan
tagline:          'Research and Stuff'
description:      'Researcher - Control Theory, Systems Biology and Power Systems.'
url:              http://yy311.github.io
baseurl:          /
cover_image:  yeyuan.jpg

author:
name:           'Ye Yuan'
email:          ye.yuan@outlook.com

paginate:         4
paginate_path:    "/notes/page:num"

# List of Pages

pages_list:
  - name: Research
    loc: /research.html
  - name: Publication
    loc: /publication.html
  - name: Teaching
    loc: /teaching.html
  
