# Dependencies
highlighter:      pygments

# Setup
title:            Ye Yuan
tagline:          'Research'
description:      'I am a Postdoc at UC Berkeley.'
url:              http://yy311.github.io
baseurl:          /
cover_image:  yeyuan.png

author:
name:           'Ye Yuan'
email:          ye.yuan@outlook.com

paginate:         3
paginate_path:    "/notes/page:num"

# List of Pages

pages_list:
  - name: Research
    loc: /research.html
  - name: Publication
    loc: /publication.html

